### PR TITLE
Enhanced UI of settings page

### PR DESCRIPTION
**Pull request by kaurjasleen240305**
Issue https://github.com/sugarlabs/make-them-fall-activity/issues/35 which aims at converting one button of difficulty into multiple buttons each for easy,medium and difficult levels

https://github.com/sugarlabs/make-them-fall-activity/assets/127110636/15656c36-e65d-429b-a8a2-a5c2efbe49ca

Screenshot (948)

Screenshot (949)
Screenshot (950)

### CODE REVIEW

**Comment by kaurjasleen240305** [comment]
Pls review @chimosky

**Comment by quozl** [comment]
Commit messages do not meet our requirements, please see https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#making-commits

Please reduce your work to one commit; there's no reason to have two, unless as the commits seem to suggest one of them was someone else's work.

Please ensure new code complies with flake8 and pep; the changes aren't compliant.

Please remove rather than comment out code.  It can always be restored by reverting the commit.

Please test and demonstrate your changes within Sugar.  The screenshots you posted show you are running the app without Sugar.  Sugar imposes various behaviours that you won't be reproducing.

Move your issue commentary into the commit messages.  I've closed the issue.

**Comment by kaurjasleen240305** [comment]
Actually @quozl very sorry I am new in open source sorry for this inconvenience I will cover all points mentioned above then again raise PR

**Comment by chimosky** [comment]
> Actually @quozl very sorry I am new in open source sorry for this inconvenience I will cover all points mentioned above then again raise PR

There's no need to be sorry, I agree with everything Quozl has said above and look forward to your contributions.

**Comment by kaurjasleen240305** [comment]
Yes @chimosky surely

**Comment by kaurjasleen240305** [comment]
Hey @chimosky @quozl can u explain what do you mean by -> Please ensure new code complies with flake8 and pep; the changes aren't compliant.
Like how to do this

**Comment by chimosky** [comment]
[Pep 8](https://pep8.org/#introduction) is the style guide for Python and one way to enforce this style is using [flake 8](https://flake8.pycqa.org/en/latest/), a lot of the changes you made weren't pep8 compliant as you didn't adhere to the style guide.

Hope that helps!

**Comment by kaurjasleen240305** [comment]
Yes @chimosky I got it so is there some guide where I could get how to follow pep8 compliancy to adhere to style guide also is there some discussion channel where I could clear my doubts .

**Comment by quozl** [comment]
Pep8 itself describes how to comply, you just have to read it or use linting tools to highlight non-compliance.

It isn't our responsibility to document, we let the Python Foundation do that.  However, these two documents are in our repositories and may help;

* https://github.com/sugarlabs/sugar-docs/blob/master/src/contributing.md#guide-for-reviewers shows what we look for as we review,
* https://github.com/sugarlabs/sugar-docs/blob/master/src/desktop-activity.md#coding-standards describes our coding standards for Python based activities, of which this repository is an example.

You can probably find a plugin for VSCode.  A quick search turned up this; https://code.visualstudio.com/docs/python/linting

I'm not using a discussion channel myself, as I'm quite busy and have other paid work that conflicts with using discussion services, but asking questions in GitHub is fine.

**Comment by kaurjasleen240305** [comment]
Ok thnx for replying @quozl

**Comment by quozl** [comment]
No worries, looking forward to your contribution.

**Pull request closed without merging**
