### PR TITLE
Refactor button creation for better maintainability

### PR DESCRIPTION
**Pull request by rajutkarsh07**
This PR refactors the button creation process to dynamically generate buttons using predefined parameters. The refactored code enhances maintainability by reducing redundancy and providing flexibility for future modifications or expansions of button configurations.

### CODE REVIEW

**Comment by rajutkarsh07** [comment]
@chimosky please review this PR

**Comment by quozl** [comment]
Why two help buttons?  Why two settings buttons?

I'm not sure this helps much, as now the information is spread between three different lists, so if something about one of the buttons needs to change there will be a long search for the relevant and connected information.

**Comment by rajutkarsh07** [comment]
@quozl 
Actually the maxscore is of length 6 so the help and the settings button are coming only once 
now I have add two more values to maxscore array now i.e. none for help and settings so I have removed the buttons that are coming outside of for loop
```
maxscores = [maxnormal, maxnightmare, maxfear, maxinferno, maximpossible, maxcardiac, None, None]
```

**Comment by rajutkarsh07** [comment]
The code is concise, with each button's properties conveniently maintained in three separate arrays just above the for loop. So there will be not much difficulty in maintaining the code

**Comment by rajutkarsh07** [comment]
we can also do this by this way
```
button_data = [
    {
        'position': (50, 26),
        'image_path': "data/images/welcomescreen/2pane.png",
        'function': lambda: self.run_game(1, "data/images/2pane.png", [[pygame.K_LEFT, pygame.K_RIGHT]]),
        'max_score': maxnormal
    },
    {
        'position': (50, 38),
        'image_path': "data/images/welcomescreen/3pane.png",
        'function': lambda: self.run_game(2, "data/images/3pane.png", [[pygame.K_LEFT, pygame.K_DOWN, pygame.K_RIGHT]]),
        'max_score': maxnightmare
    },
    {
        'position': (20, 38),
        'image_path': "data/images/welcomescreen/4pane.png",
        'function': lambda: self.run_game(3, "data/images/4pane.png", [[pygame.K_a, pygame.K_d], [pygame.K_LEFT, pygame.K_RIGHT]]),
        'max_score': maxfear
    },
    {
        'position': (80, 38),
        'image_path': "data/images/welcomescreen/5pane.png",
        'function': lambda: self.run_game(4, "data/images/5pane.png", [[pygame.K_a, pygame.K_s, pygame.K_d], [pygame.K_LEFT, pygame.K_RIGHT]]),
        'max_score': maxinferno
    },
    {
        'position': (50, 50),
        'image_path': "data/images/welcomescreen/6pane.png",
        'function': lambda: self.run_game(5, "data/images/6pane.png", [[pygame.K_a, pygame.K_s, pygame.K_d], [pygame.K_LEFT, pygame.K_DOWN, pygame.K_RIGHT]]),
        'max_score': maximpossible
    },
    {
        'position': (50, 62),
        'image_path': "data/images/welcomescreen/2paneheart.png",
        'function': lambda: self.run_game(6, "data/images/2pane.png", [[pygame.K_LEFT, pygame.K_RIGHT]], type_="cardiac"),
        'max_score': maxcardiac
    },
    {
        'position': (25, 75),
        'image_path': "data/images/welcomescreen/help.png",
        'function': self.show_help,
        'max_score': None
    },
    {
        'position': (75, 75),
        'image_path': "data/images/welcomescreen/settings.png",
        'function': self.show_settings,
        'max_score': None
    }
]

for button_info in button_data:
    position = button_info['position']
    image_path = button_info['image_path']
    function = button_info['function']
    max_score = button_info['max_score']
    
    x, y = position
    self.buttons.append(Button(self.vw(x), self.vh(y), image_path, function, max_score))

```

**Comment by quozl** [comment]
Commit 92d0896 ("added dark mode") only has delete of an empty line before main.

**Comment by rajutkarsh07** [comment]
sorry @quozl
Actually I was working on the dark mode of this app in a different branch 
but by mistake I have commited in this branch

**Comment by rajutkarsh07** [comment]
@quozl 
is the new code for the button is fine now?

**Comment by quozl** [comment]
It is obscure that you use zip to ignore the tail of the long lists because there is a shorter list, combined with two sets of coding for the help and settings buttons.  I don't think this obscurity is helpful.

**Comment by rajutkarsh07** [comment]
@quozl @chimosky please check this one.

**Comment by chimosky** [comment]
> @quozl @chimosky please check this one.

Haven't tested, Quozl made a comment above which you're yet to address.

**Comment by rajutkarsh07** [comment]
@chimosky done

**Comment by rajutkarsh07** [comment]
@chimosky @quozl I have made it pep8 compliant

**Comment by rajutkarsh07** [comment]
@chimosky @quozl I have made it pep8 compliant

**Pull request merged**
